### ISSUE TITLE
A* Algorithm 

### ISSUE THREAD

**Issue by 19-ade** [devanshdhrafani/rrt-rrt-star#3]
Is there a scope of applying A* Algorithm here ? We can still find the shortest path between the two point s

**Comment by devanshdhrafani** [comment]
Yes. That's a potential task that can be taken up. RRT/RRT* is used to explore the environment, but you need a shortest path algorithm like D* or A* to reach the goal in minimum time.

**Comment by 19-ade** [comment]
Great!!!
